theme = "slick"
icons = "awesome"

[[block]]
block = "custom"
interval = 60
command = "cat /sys/class/power_supply/BAT0/capacity"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "time"
interval = 60
format = "%a %y/%m/%d %R"
