export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

[[ -z "$TMUX" && ! -z "$PS1" ]] && exec tmux

if [[ ! -d ~/.zplug ]];then
  git clone https://github.com/zplug/zplug ~/.zplug
fi

source ~/.zplug/init.zsh

# enhancd config
export ENHANCD_COMMAND=ed
export ENHANCD_FILTER=ENHANCD_FILTER=fzy:fzf:peco

zplug "aperezdc/zsh-fzy"

# Vanilla shell
zplug "yous/vanilli.sh"

# Additional completion definitions for Zsh
zplug "zsh-users/zsh-completions"

# Load the theme.
zplug "denysdovhan/spaceship-prompt", use:spaceship.zsh, from:github, as:theme

# Syntax highlighting bundle. zsh-syntax-highlighting must be loaded after
# excuting compinit command and sourcing other plugins.
zplug "zsh-users/zsh-syntax-highlighting", nice:9

# ZSH port of Fish shell's history search feature
zplug "zsh-users/zsh-history-substring-search", nice:10

# Tracks your most used directories, based on 'frecency'.
zplug "rupa/z", use:"*.sh"

# A next-generation cd command with an interactive filter
zplug "b4b4r07/enhancd", use:init.sh

# This plugin adds many useful aliases and functions.
zplug "plugins/git",   from:oh-my-zsh

zplug "aperezdc/zsh-fzy"

# Then, source plugins and add commands to $PATH
zplug load

# ALT-C: cd into the selected directory
# CTRL-T: Place the selected file path in the command line
# CTRL-R: Place the selected command from history in the command line
bindkey '\ec' fzy-cd-widget
bindkey '^T'  fzy-file-widget
bindkey '^R'  fzy-history-widget

zstyle :fzy:tmux    enabled      no

zstyle :fzy:history show-scores  no
zstyle :fzy:history lines        10
zstyle :fzy:history prompt       'history >> '

zstyle :fzy:file    show-scores  no
zstyle :fzy:file    lines        10
zstyle :fzy:file    prompt       'file >> '

zstyle :fzy:cd      show-scores  no
zstyle :fzy:cd      lines        10
zstyle :fzy:cd      prompt       'cd >> '

# Better history searching with arrow keys
if zplug check "zsh-users/zsh-history-substring-search"; then
    bindkey "$terminfo[kcuu1]" history-substring-search-up
    bindkey "$terminfo[kcud1]" history-substring-search-down
fi

# Add color to ls command
export CLICOLOR=1

# Set GOPATH for Go
if command -v go &> /dev/null; then
  [ -d "$HOME/go" ] || mkdir "$HOME/go"
  export GOPATH="$HOME/go"
  export PATH="$PATH:$GOPATH/bin:$GOROOT/bin"
fi

export PATH=$HOME/bin:$PATH

# nodejs
if command -v yarn &> /dev/null; then
  export PATH="$PATH:$HOME/.yarn/bin/"
fi

alias ls='ls --color=auto'
alias l="ls -al"
alias vim="nvim"
alias vi="nvim"
