export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

eval "$(starship init zsh)"

autoload -U select-word-style
select-word-style bash

# Initialize the autocompletion
autoload -Uz compinit && compinit -i

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node \
    yous/vanilli.sh \
    zsh-users/zsh-autosuggestions \
    zdharma/fast-syntax-highlighting \
    zsh-users/zsh-completions

### End of Zinit's installer chunk

fzy-history-widget() {
    local selected num
    selected=( $(fc -l 1 | fzy -s -q "${LBUFFER//$/\\$}") )
    if [ -n "$selected" ]; then
        num=$selected[1]
        if [ -n "$num" ]; then
            zle vi-fetch-history -n $num
        fi
    fi
    zle redisplay
}
zle -N fzy-history-widget
bindkey '^R' fzy-history-widget

# Add color to ls command
export CLICOLOR=1

# Set GOPATH for Go
if command -v go &> /dev/null; then
  [ -d "$HOME/go" ] || mkdir "$HOME/go"
  export GOPATH="$HOME/go"
  export PATH="$PATH:$GOPATH/bin:$GOROOT/bin"
fi

export PATH=$HOME/.poetry/bin:$HOME/bin:$HOME/.pub-cache/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH
export ARDROID_HOME=$HOME/Android/Sdk/

# nodejs
if command -v yarn &> /dev/null; then
  export PATH="$PATH:$HOME/.yarn/bin/"
fi

alias ls='lsd --color=auto'
alias l="lsd -al"
alias vim="nvim"
alias vi="nvim"

unsetopt BEEP
